export const ActionTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  FETCH_USER: "FETCH_USER",
  UPDATE_USER: "UPDATE_USER",
  SET_USER: "SET_USER",
  CURRENT_USER: "CURRENT_USER",
};
